before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - id: hcledit
    binary: bin/hcledit
    dir: cmd/hcledit
    ldflags:
      - -s -w
      - -X go.mercari.io/hcledit/cmd/hcledit/internal/version.Version={{.Tag}}
      - -X go.mercari.io/hcledit/cmd/hcledit/internal/version.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'      
      - Merge pull request
      - Merge branch
brews:
  - tap:
      owner: mercari
      name: hcledit
    folder: Formula
    homepage: https://github.com/mercari/hcledit
    description: CLI to edit HCL configurations
    install: 'bin.install "bin/hcledit"'
