version: 2
before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - id: hcledit
    binary: bin/hcledit
    dir: cmd/hcledit
    ldflags:
      - -s -w
      - -X go.mercari.io/hcledit/cmd/hcledit/internal/version.Version={{.Tag}}
      - -X go.mercari.io/hcledit/cmd/hcledit/internal/version.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
brews:
  - repository:
      owner: mercari
      name: hcledit
      pull_request:
        enabled: true
        base:
          owner: mercari
          name: hcledit
          branch: main
    directory: Formula
    homepage: https://github.com/mercari/hcledit
    description: CLI to edit HCL configurations
