# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcledit < Formula
  desc "CLI to edit HCL configurations"
  homepage "https://github.com/mercari/hcledit"
  version "0.0.8"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.8/hcledit_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "5579be59e4270026394d04ee7707a73e1c033780cac224e6f67ecf2d606a9f20"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.8/hcledit_0.0.8_Linux_x86_64.tar.gz"
    sha256 "b5a326659a8e087458812db8c6d4f731073562104c4d3a18f53b75e77aaf2a36"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.8/hcledit_0.0.8_Linux_arm64.tar.gz"
    sha256 "2ccc7f4d11cea0fd3c10b71ecc8c82a0faf184895775875dcf7f61f6092e37f4"
  end

  def install
    bin.install "hcledit"
  end
end
