# This file was generated by GoReleaser. DO NOT EDIT.
class Hcledit < Formula
  desc "CLI to edit HCL configurations"
  homepage "https://github.com/mercari/hcledit"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.7/hcledit_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "382db425f3f374dc8d5bb95a6086d7d48bf16d94f81c037505a54dcc07ca7bd9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.7/hcledit_0.0.7_Linux_x86_64.tar.gz"
    sha256 "a743dd0eb901e53a8d7a30d83dacff51863809ceccb02f0d7089818f84c88b4f"
  end

  def install
    bin.install "bin/hcledit"
  end
end
