# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcledit < Formula
  desc "CLI to edit HCL configurations"
  homepage "https://github.com/mercari/hcledit"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.6/hcledit_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "cbe8a0a963a3ac16b010d114d94b8fcfb5f9763684d8e9a02e6209bf287fce41"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.6/hcledit_0.0.6_Linux_x86_64.tar.gz"
    sha256 "3efcd783195bc5e09a6f394168e5837fa77e4bdc2f36d90323f2dc87476ce534"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mercari/hcledit/releases/download/v0.0.6/hcledit_0.0.6_Linux_arm64.tar.gz"
    sha256 "45fd3dadb16bc0cc05115a02cc85aa7252a5b5052a0eb2362dc8938dc1506399"
  end

  def install
    bin.install "hcledit"
  end
end
