name: Lint

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2
